- name: Create directory test-ansible
  file:
    path: /home/{{ user }}/test-ansible
    state: absent
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: Create directory .local/bin
  file:
    path: /home/{{ user }}/.local/bin
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0754
