# - name: Install kubectl
#   unarchive:
#     src: https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl
#     dest: /home/bob_henkel/test-ansible
#     remote_src: yes
- name: Download and install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl
    dest: /home/bhenkel/.local/bin/kubectl
    checksum: sha256:4314fb34e46be9b5558eea014060d8283a82074b33366e4163e5afaa69ddae23
    owner: bhenkel
    group: bhenkel
    mode: 0755

- name: Download and install goss
  get_url:
    url: https://github.com/aelsabbahy/goss/releases/download/v0.3.6/goss-linux-amd64
    dest: /home/bhenkel/.local/bin/goss
    checksum: sha256:53dd1156ab66f2c4275fd847372e6329d895cfb2f0bcbec5f86c1c4df7236dde
    owner: bhenkel
    group: bhenkel
    mode: 0755
    
    
- name: Download and install stern
  get_url:
    url: https://github.com/wercker/stern/releases/download/1.10.0/stern_linux_amd64
    dest: /home/bhenkel/.local/bin/stern
    checksum: sha256:a0335b298f6a7922c35804bffb32a68508077b2f35aaef44d9eb116f36bc7eda
    owner: bhenkel
    group: bhenkel
    mode: 0755

- name: Download pulumi tarball
  get_url:
    url: https://github.com/pulumi/pulumi/archive/v0.16.9.tar.gz
    dest: /tmp/pulumi.tar.gz
    checksum: sha256:79b00069d61cef927ff23fa9f8620c5c177f1323d2d0065903ee26b9df3f6858
    
- name: Extract /tmp/pulumi.tar.gz to ~/.local/bin
  unarchive:
    src: /tmp/pulumi.tar.gz
    dest: /home/bhenkel/.local/bin
    
- name: Install docker engine
  shell: |
    apt-get update
    
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    apt-key fingerprint 0EBFCD88
    add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"

    apt-get update
    apt-get install -y docker-ce

    groupadd docker
    usermod -aG docker bhenkel

# - name: Download and install pet
#   get_url:
#     url: https://github.com/knqyf263/pet/releases/download/v0.3.2/pet_0.3.2_linux_amd64.tar.gz
#     dest: /home/bhenkel/.local/bin/pet
#     checksum: sha256:58e800718f05d8ceea3c230b0d871c25d33926bd5541567b113fa56be6143c41
#     owner: bhenkel
#     group: bhenkel
#     mode: 0755

- name: install taskbook via snap
  command: snap install taskbook
#TODO 
#slack
#zoom
#chrome
#flatpack
#authenticator
