# - name: Install kubectl
#   unarchive:
#     src: https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl
#     dest: /home/bob_henkel/test-ansible
#     remote_src: yes
- name: Download and install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl
    dest: /home/bob_henkel/.local/bin/kubectl
    checksum: sha256:4314fb34e46be9b5558eea014060d8283a82074b33366e4163e5afaa69ddae23
    owner: bob_henkel
    group: bob_henkel
    mode: 0755
