- name: apt update
  apt: update_cache=yes cache_valid_time=3600
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  sudo: yes
  ignore_errors: yes

- name: retry if needed using command apt-get update
  command: apt-get update
  register: apt_update
  sudo: yes
  when: apt_result|failed

# # Add specified repository into sources list using specified filename.
# - apt_repository:
#     repo: deb https://deb.etcher.io stable etcher
#     state: present
#     filename: etcher

# - name: Add/Trust Bintray.com's GPG key
#   apt_key: 
#     keyserver: keyserver.ubuntu.com 
#     id: 379CE192D401AB61
#   become: yes
#   when: apt_update|succeeded

- name: Install packages
  apt: name={{item}}
  with_items:
    - htop
    - mc
    - tmux
    - fish
    - httpie
    - etcher-electron
