- name: Add/Trust Bintray.com's GPG key
  apt_key: 
    keyserver: keyserver.ubuntu.com 
    id: 379CE192D401AB61
  become: yes
#   when: apt_update|succeeded
  
# - name: apt update
#   apt: update_cache=yes cache_valid_time=3600
#   register: apt_result
#   until: apt_result|success
#   retries: 3
#   delay: 1
#   sudo: yes
#   ignore_errors: yes

# - name: retry if needed using command apt-get update
#   command: apt-get update
#   register: apt_update
#   sudo: yes
#   when: apt_result|failed

# Add specified repository into sources list using specified filename.
- apt_repository:
    repo: deb https://deb.etcher.io stable etcher
    state: present
    filename: etcher

#RUNDECK CLI
- apt_repository:
    repo: deb https://dl.bintray.com/rundeck/rundeck-deb /
    state: present

- name: Download bintray.gpg.key
  get_url:
    url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
    dest: /tmp/bintray.gpg.key
    
- name: Add Apt signing key on remote server to keyring
  apt_key:
    file: /tmp/bintray.gpg.key
    state: present
  
# Not in 18.10 repo yet
# - apt_repository:
#     repo: ppa:alexlarsson/flatpak
#     state: present

# - name: Install the Authenticator app from flathub for current user
#   flatpak:
#     name: com.github.bilelmoussaoui.Authenticator
#     state: present
    
- name: Install a bat .deb package from github
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.9.0/bat_0.9.0_amd64.deb

- name: Install a vscode .deb package from microsoft
  apt:
    deb: https://az764295.vo.msecnd.net/stable/61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8/code_1.30.2-1546901646_amd64.deb

- name: Install packages
  apt: name={{item}}
  with_items:
    - htop
    - mc
    - tmux
    - fish
    - httpie
    - etcher-electron
    - kubectx
    - gnome-tweak-tool
    - mypaint
    - default-jre
    - apt-transport-https
    - rundeck-cli
    - jq
    - krita
